name: matrix

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        microservices: [ "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create snapshot
        id: snapshot
        shell: bash
        run: | 
          echo "test-snapshot-${{ matrix.microservice }}::${{ matrix.microservices }}" >> $GITHUB_OUTPUT

  onlyone:
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: echo
        run: |
          echo "${{ steps.snapshot.outputs.test-snapshot-jan }}, ${{ steps.snapshot.outputs.test-snapshot-feb }}"