name: matrix

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        microservices: [ "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: output
        id: test-output
        shell: bash
        run: | 
          echo "::set-output name=test-name-output::${{ matrix.microservices }}"

      - name: echo
        run: |
          echo "${{ steps.test-output.outputs.test-name-output }}"

  onlyone:
    runs-on: ubuntu-20.04
    needs: [test]
    strategy:
      matrix:
        microservices: [ "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug" ]
    steps:
      - name: echo
        run: |
          echo "${{ steps.test-output.outputs.test-name-output }}"