name: matrix

on:
  workflow_dispatch:
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        microservices: [ "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug" ]

    outputs:
      ${{ matrix.microservices }}: ${{ steps.snapshot.outputs.test-snapshot }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create snapshot
        id: snapshot
        shell: bash
        run: | 
          echo "test-snapshot=${{ matrix.microservices }}" >> $GITHUB_OUTPUT

  onlyone:
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: echo
        run: |
          echo "${{ needs.test.outputs.jan }}, ${{ needs.test.outputs.feb }}"